# Generated by Django 4.2.24 on 2025-11-24 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_segmenthistory_userdata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerData',
        ),
    ]
