# Generated by Django 4.2.24 on 2025-11-24 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_delete_customerdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='phone_number',
            new_name='keywords',
        ),
        migrations.RemoveField(
            model_name='userdata',
            name='name',
        ),
    ]
