# Generated by Django 4.2.24 on 2025-11-09 09:49

from django.db import migrations, models
import pgvector.django.vector


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InsightDocVec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_id', models.TextField(null=True)),
                ('chunk_index', models.IntegerField(null=True)),
                ('content', models.TextField(null=True)),
                ('embedding', pgvector.django.vector.VectorField(dimensions=1024, null=True)),
            ],
            options={
                'db_table': 'insight_docvec',
                'managed': True,
            },
        ),
    ]
