# Generated by Django 4.2.24 on 2025-11-24 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insightdocvec',
            name='query_text',
            field=models.TextField(help_text='이 문서 벡터를 생성하게 만든 자연어 검색 질의', null=True),
        ),
    ]
