# Generated by Django 4.2.24 on 2025-11-24 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insight', '0002_insightdocvec_query_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insightdocvec',
            name='query_text',
        ),
    ]
